services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ~/data/mongo/db:/data/db
      - ~/data/mongo/log:/data/log
      - ~/data/mongo/conf/mongod.conf:/etc/mongod.conf
    command: mongod --config /etc/mongod.conf
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ~/data/redis:/data
      - ~/data/redis/redis.conf:/usr/local/etc/redis/redis.conf
  api:
    container_name: api
    build: .
    depends_on:
      - mongo
      - redis
    ports:
      - 3000:3000
    env_file: .env
    command: node ./build/index.js
    # command: pm2 ./build/index.js
